info:
  title: Inventory API
  version: v1
openapi: 3.1.0
components:
  schemas: {}
  parameters: {}
tags:
  - name: warehouse
    description: Everything about the Warehouse
  - name: movement
    description: Start and finish the movement
paths:
  /warehouse/assign:
    post:
      tags:
        - warehouse
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                code:
                  type: string
              required:
                - name
                - code
      responses:
        '200':
          description: Success message

  /movement/start:
    post:
      tags:
        - movement
      responses:
        '200':
          description: Success message
  /movement/item:
    post:
      tags:
        - movement
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
              required:
                - code
      responses:
        '200':
          description: Success message
    delete:
      tags:
        - movement
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: string
              required:
                - code
      responses:
        '200':
          description: Success message
