name: ci

on:
  push:
    branches:
      - "*"
      - "!master"
  pull_request:

jobs:
  build-deploy-web:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      deployments: write
    defaults:
      run:
        working-directory: ./web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: ./web/package-lock.json
      - run: npm ci
      - run: npm run build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: kolenka-inc
          SENTRY_PROJECT: inventory
      - uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: "web"
          environment: preview
          command: |
            pages deploy dist --project-name=inventory-web

  build-deploy-api:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      checks: write
      id-token: write
      pull-requests: write
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: ./api/package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm run test
      - name: Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # run this step even if previous step failed
        with:
          report_paths: ./api/junit.xml # Path to test results
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Coverage Report
        uses: romeovs/lcov-reporter-action@v0.4.0
        if: success() || failure() # run this step even if previous step failed
        with:
          lcov-file: ./api/coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: kolenka-inc
          SENTRY_PROJECT: inventory
      - run: npm run migrate:up
        env:
          WRANGLER_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE: ${{ secrets.WRANGLER_HYPERDRIVE_LOCAL_CONNECTION_STRING_HYPERDRIVE }}
          AIVEN_CA: ${{ secrets.AIVEN_CA }}
      - uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: "api"
          environment: staging
          secrets: |
            ELASTICSEARCH_LOGIN
            ELASTICSEARCH_PASSWORD
        env:
          ELASTICSEARCH_LOGIN: ${{ secrets.ELASTICSEARCH_LOGIN }}
          ELASTICSEARCH_PASSWORD: ${{ secrets.ELASTICSEARCH_PASSWORD }}
