import {
  GoogleSpreadsheet,
  GoogleSpreadsheetWorksheet
} from 'google-spreadsheet';
import { JWT } from 'google-auth-library';
import type { GoogleServiceAccountCredentials } from './google-objects';

export class InventoryManagementStore {
  private document: GoogleSpreadsheet;

  constructor(
    googleServiceAccountCredentials: GoogleServiceAccountCredentials,
    googleSheetId: string
  ) {
    // Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
    const serviceAccountAuth = new JWT({
      // env var values here are copied from service account credentials generated by google
      // see "Authentication" section in docs for more info
      email: googleServiceAccountCredentials.client_email,
      key: googleServiceAccountCredentials.private_key,
      scopes: ['https://www.googleapis.com/auth/spreadsheets']
    });
    this.document = new GoogleSpreadsheet(googleSheetId, serviceAccountAuth);
  }

  public async getLastSheetNameAsync(): Promise<string> {
    await this.document.loadInfo();
    const page =
      await this.document.sheetsByIndex[this.document.sheetCount - 1];
    return page.title;
  }

  public async addToLastSheetAsync(
    name: string,
    code: string
  ): Promise<boolean> {
    const page =
      await this.document.sheetsByIndex[this.document.sheetCount - 1];
    await page.addRow({
      name,
      code
    });
    return true;
  }

  public async getNameOfItemAsync(code: string): Promise<string> {
    const inventorySheet =
      await this.document.sheetsByIndex[this.document.sheetCount - 1];
    const allItems = await inventorySheet.getRows();
    const item = allItems.find((row) => row.get('code') === code);
    if (item === undefined) {
      throw Error(`There is no Item with ${code} code`);
    }
    return item.get('name');
  }

  public async getDateOfFirstListAsync(): Promise<Date> {
    await this.document.loadInfo();
    const firstPage = await this.document.sheetsByIndex[0];
    return new Date(firstPage.title);
  }

  public async startSessionAsync(): Promise<boolean> {
    await this.document.loadInfo();
    return true;
  }

  public async getSheetsCountAsync(): Promise<number> {
    return this.document.sheetCount;
  }

  public getSheetsByIndex(index: number): GoogleSpreadsheetWorksheet {
    return this.document.sheetsByIndex[index];
  }

  public async createNewMovementSheetAsync(title: string): Promise<boolean> {
    await this.document.addSheet({
      title,
      headerValues: ['code', 'item', 'departured', 'arrived'],
      index: 0
    });
    return true;
  }

  public async addItemToDeparturesAsync(
    code: string,
    dateTime: string
  ): Promise<boolean> {
    console.log(`code: ${code}, time: ${dateTime}`);
    const inventorySheet =
      this.document.sheetsByIndex[this.document.sheetCount - 1];
    console.log('I got inventorySheet. Gonna to retrieve all items');
    const allItems = await inventorySheet.getRows();
    console.log('Lets try to find the item by the code');
    const item = allItems.find((row) => row.get('code') === code);
    if (item != null) {
      console.log(`Item was found: ${item.get('item')}`);
      const currentSheet = await this.document.sheetsByIndex[0];
      console.log('Im going to add the row');
      await currentSheet.addRow({
        code: code,
        item: item.get('name'),
        departured: `="${dateTime}"`,
        arrived: ''
      });
      return true;
    } else {
      console.log('Item was not found');
      return false;
    }
  }

  public async addItemToArrivalsAsync(
    code: string,
    dateTime: string
  ): Promise<boolean> {
    console.log(`code: ${code}, time: ${dateTime}`);
    const currentSheet = this.document.sheetsByIndex[0];
    console.log('I got inventorySheet. Gonna to retrieve all items');
    const allItems = await currentSheet.getRows();
    console.log('Lets try to find the item by the code');
    const item = allItems.find((row) => row.get('code') === code);
    if (item != null) {
      console.log(`Item was found: ${item.get('item')}`);
      console.log('Im going to add the row');
      item.set('arrived', `="${dateTime}"`);
      await item.save();
      return true;
    } else {
      console.log('Item was not found');
      return false;
    }
  }
}
